## Prometheus server config — federated across both regions.
## In primary, scrapes local cluster + receives federated metrics from DR.

global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    cluster: sentinelgrid-primary
    region:  us-east-1

alerting:
  alertmanagers:
    - static_configs: [{ targets: ['alertmanager.sg-observability.svc:9093'] }]

rule_files:
  - /etc/prometheus/rules/*.yaml

scrape_configs:
  - job_name: kubernetes-pods
    kubernetes_sd_configs: [{ role: pod }]
    relabel_configs:
      - { source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape], action: keep, regex: "true" }
      - { source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path],   action: replace, target_label: __metrics_path__, regex: "(.+)" }
      - { source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port], action: replace, target_label: __address__, regex: "([^:]+)(?::\\d+)?;(\\d+)", replacement: "$1:$2" }
      - { source_labels: [__meta_kubernetes_namespace], target_label: namespace }
      - { source_labels: [__meta_kubernetes_pod_name], target_label: pod }
      - { source_labels: [__meta_kubernetes_pod_label_app], target_label: app }

  - job_name: kubernetes-nodes-cadvisor
    scheme: https
    tls_config: { ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt }
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs: [{ role: node }]
    relabel_configs:
      - { source_labels: [__address__], target_label: __address__, replacement: kubernetes.default.svc:443 }
      - { source_labels: [__meta_kubernetes_node_name], target_label: __metrics_path__, regex: "(.+)", replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor }

  - job_name: blackbox-probes
    metrics_path: /probe
    params: { module: [http_2xx] }
    static_configs:
      - targets:
          - https://api.sentinelgrid.gov/healthz
          - https://console.sentinelgrid.gov/
    relabel_configs:
      - { source_labels: [__address__], target_label: __param_target }
      - { source_labels: [__param_target], target_label: instance }
      - { target_label: __address__, replacement: blackbox-exporter.sg-observability.svc:9115 }

  - job_name: federate-dr
    honor_labels: true
    metrics_path: /federate
    params: { 'match[]': ['{job=~".+"}'] }
    static_configs: [{ targets: ['prometheus.dr.sentinelgrid.internal:9090'] }]
